export const clerkAppearance = {
  variables: {
    colorPrimary: '#FFD700',
    colorBackground: '#1A1A1A',
    colorText: '#FFFFFF',
    colorInputBackground: '#1A1A1A',
    colorInputText: '#FFFFFF',
    colorTextOnPrimaryBackground: '#111111',
    colorTextSecondary: 'rgba(255, 255, 255, 0.60)',
    colorNeutral: 'rgba(255, 255, 255, 0.10)',
    colorMuted: 'transparent',
    shadowShimmer: 'transparent',
    shadowFocus: 'transparent',
    shadowPrimary: 'transparent',
    fontFamily: 'Inter, Roboto, Helvetica, Arial, sans-serif',
    borderRadius: '8px',
    fontSize: '16px',
    colorAccent: '#FFFFFF',
  },
  elements: {
    card: 'bg-transparent border-none shadow-none !bg-transparent [box-shadow:none!important] [box-shadow:0_0_0_transparent!important]',
    headerTitle: 'text-white font-semibold text-xl mb-1',
    headerSubtitle: 'text-[rgba(255,255,255,0.60)] text-xs mb-6',
    formButtonPrimary: 'bg-[#FFD700] text-[#111111] hover:bg-[#FFEF5C] font-bold rounded-[35px] transition-colors border-none text-base py-4 px-8 mt-2',
    formButtonSecondary: 'border-[rgba(255,255,255,0.20)] text-white hover:bg-[rgba(255,215,0,0.1)] hover:border-[#FFD700] rounded-[35px] transition-colors py-4 px-8',
    socialButtonsBlockButton: 'bg-[rgba(255,255,255,0.05)] border-[rgba(255,255,255,0.20)] text-white hover:bg-[rgba(255,215,0,0.1)] hover:border-[#FFD700] rounded-[35px] transition-colors py-4 px-8',
    formFieldInput: 'bg-[rgba(255,255,255,0.05)] text-white placeholder:text-[rgba(255,255,255,0.40)] focus:border-[#FFD700] rounded-lg text-base mb-4 [border:2px_solid_rgba(255,255,255,0.4)!important] [padding:16px_20px!important] [outline:none!important]',
    formFieldLabel: 'text-white font-medium text-sm',
    identityPreviewText: 'text-white',
    identityPreviewEditButton: 'text-[#278EFF] hover:text-[#FFD700]',
    footerActionText: 'bg-transparent [background:transparent!important]',
    footerActionLink: 'text-[#278EFF] hover:text-[#FFD700] bg-transparent [background:transparent!important]',
    dividerLine: 'bg-[rgba(255,255,255,0.10)]',
    dividerText: 'text-[rgba(255,255,255,0.60)]',
    alertText: 'text-white',
    formFieldSuccessText: 'text-[#FFD700]',
    formFieldErrorText: 'text-[#ff6b6b]',
    footer: 'bg-transparent border-none shadow-none !bg-transparent [background:transparent!important] [background-image:none!important]',
    footerPages: 'bg-transparent !bg-transparent [background:transparent!important]',
    footerAction: 'bg-transparent !bg-transparent [background:transparent!important]',
    cardBox: '[box-shadow:none!important]',
    main: '[box-shadow:none!important]',
    signInStart: '[box-shadow:none!important]',
    internal8d3o8p: '[border:2px_solid_rgba(255,255,255,0.4)!important] [padding:16px_20px!important] [outline:none!important]',
    formFieldInput__checkbox: 'border-[rgba(255,255,255,0.4)] bg-[rgba(255,255,255,0.05)] accent-[#FFD700]',
    formFieldInputShowPasswordButton: 'text-white hover:text-[#FFD700]',
    formFieldOptionalInput: 'border-[rgba(255,255,255,0.4)] bg-[rgba(255,255,255,0.05)]',
    formFieldCheckboxLabel: 'text-sm text-[rgba(255,255,255,0.70)]',
    formFieldCheckboxLabelText: 'text-sm',
    formFieldAction: 'text-sm',
    formFieldHintText: 'text-xs text-[rgba(255,255,255,0.50)]',
    formFieldInput__emailCode: 'bg-[rgba(255,255,255,0.05)] border-[rgba(255,255,255,0.4)] text-white text-center font-bold text-lg',
    formFieldInput__phoneCode: 'bg-[rgba(255,255,255,0.05)] border-[rgba(255,255,255,0.4)] text-white text-center font-bold text-lg',
    formFieldInput__backup_code: 'bg-[rgba(255,255,255,0.05)] border-[rgba(255,255,255,0.4)] text-white text-center font-bold text-lg',
    userButtonPopoverActionButton: 'text-white hover:text-[#FFD700] [color:white!important] [--accent:white!important]',
    userButtonPopoverActionButtonText: 'text-white [color:white!important]',
    userButtonPopoverActions: '[--accent:white!important]',
  },
};
