// Generated by scripts/generate-design-tokens.js. Do not edit directly.
export const tokens = {
  "color": {
    "author": {
      "albertBarnes": {
        "$type": "color",
        "$value": "#e9249a"
      },
      "atRobertson": {
        "$type": "color",
        "$value": "#5b41de"
      },
      "augustine": {
        "$type": "color",
        "$value": "#00d18f"
      },
      "charlesEllicott": {
        "$type": "color",
        "$value": "#9342f7"
      },
      "charlesSpurgeon": {
        "$type": "color",
        "$value": "#278eff"
      },
      "expositorsBible": {
        "$type": "color",
        "$value": "#de9a41"
      },
      "johnCalvin": {
        "$type": "color",
        "$value": "#ffd427"
      },
      "johnGill": {
        "$type": "color",
        "$value": "#22c55e"
      },
      "martinLuther": {
        "$type": "color",
        "$value": "#ff6040"
      },
      "matthewHenry": {
        "$type": "color",
        "$value": "#ff272b"
      },
      "thomasAquinas": {
        "$type": "color",
        "$value": "#ea8724"
      }
    },
    "base": {
      "neutrals": {
        "50": {
          "$type": "color",
          "$value": "#faf9f6"
        },
        "100": {
          "$type": "color",
          "$value": "#e4e4e1"
        },
        "200": {
          "$type": "color",
          "$value": "#d5d4d1"
        },
        "300": {
          "$type": "color",
          "$value": "#bab9b6"
        },
        "400": {
          "$type": "color",
          "$value": "#949391"
        },
        "500": {
          "$type": "color",
          "$value": "#6c6b6a"
        },
        "600": {
          "$type": "color",
          "$value": "#3a3938"
        },
        "700": {
          "$type": "color",
          "$value": "#312f2e"
        },
        "800": {
          "$type": "color",
          "$value": "#1e1d1c"
        },
        "900": {
          "$type": "color",
          "$value": "#0e0d0b"
        },
        "alpha": {
          "black40": {
            "$type": "color",
            "$value": "rgba(14, 13, 11, 0.4)"
          }
        }
      },
      "primary": {
        "50": {
          "$type": "color",
          "$value": "#fffbe7"
        },
        "100": {
          "$type": "color",
          "$value": "#fff8d6"
        },
        "200": {
          "$type": "color",
          "$value": "#fff1a8"
        },
        "300": {
          "$type": "color",
          "$value": "#ffe97a"
        },
        "400": {
          "$type": "color",
          "$value": "#ffd700"
        },
        "500": {
          "$type": "color",
          "$value": "#e6c200"
        },
        "600": {
          "$type": "color",
          "$value": "#bfa200"
        },
        "700": {
          "$type": "color",
          "$value": "#8c7700"
        },
        "800": {
          "$type": "color",
          "$value": "#5a4d00"
        },
        "900": {
          "$type": "color",
          "$value": "#3b3300"
        }
      },
      "states": {
        "failure": {
          "$type": "color",
          "$value": "#fff1a8"
        },
        "success": {
          "$type": "color",
          "$value": "#fffbe7"
        },
        "warning": {
          "$type": "color",
          "$value": "#fff8d6"
        }
      }
    },
    "semantic": {
      "action": {
        "primary": {
          "active": {
            "$type": "color",
            "$value": "{color.base.primary.500}"
          },
          "border": {
            "$type": "color",
            "$value": "{color.base.primary.300}"
          },
          "disabled": {
            "icon": {
              "$type": "color",
              "$value": "{color.base.neutrals.900}"
            },
            "surface": {
              "$type": "color",
              "$value": "{color.base.primary.700}"
            },
            "text": {
              "$type": "color",
              "$value": "{color.base.neutrals.900}"
            }
          },
          "hover": {
            "$type": "color",
            "$value": "{color.base.primary.300}"
          },
          "surface": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "text": {
            "$type": "color",
            "$value": "{color.base.neutrals.900}"
          }
        },
        "secondary": {
          "active": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          },
          "border": {
            "$type": "color",
            "$value": "{color.base.neutrals.600}"
          },
          "disabled": {
            "icon": {
              "$type": "color",
              "$value": "{color.base.neutrals.400}"
            },
            "surface": {
              "$type": "color",
              "$value": "{color.base.neutrals.800}"
            },
            "text": {
              "$type": "color",
              "$value": "{color.base.neutrals.400}"
            }
          },
          "hover": {
            "$type": "color",
            "$value": "{color.base.neutrals.600}"
          },
          "surface": {
            "$type": "color",
            "$value": "{color.base.neutrals.700}"
          },
          "text": {
            "$type": "color",
            "$value": "{color.base.neutrals.50}"
          }
        }
      },
      "background": {
        "canvas": {
          "$type": "color",
          "$value": "{color.base.neutrals.900}"
        },
        "overlay": {
          "scrim": {
            "$type": "color",
            "$value": "{color.base.neutrals.alpha.black40}"
          }
        },
        "surface": {
          "inverse": {
            "$type": "color",
            "$value": "{color.base.neutrals.100}"
          },
          "muted": {
            "$type": "color",
            "$value": "{color.base.neutrals.600}"
          },
          "primary": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          },
          "secondary": {
            "$type": "color",
            "$value": "{color.base.neutrals.700}"
          }
        }
      },
      "border": {
        "default": {
          "$type": "color",
          "$value": "{color.base.neutrals.600}"
        },
        "disabled": {
          "$type": "color",
          "$value": "{color.base.neutrals.800}"
        },
        "inverse": {
          "$type": "color",
          "$value": "{color.base.neutrals.100}"
        },
        "strong": {
          "$type": "color",
          "$value": "{color.base.neutrals.500}"
        },
        "subtle": {
          "$type": "color",
          "$value": "{color.base.neutrals.700}"
        }
      },
      "content": {
        "icon": {
          "inverse": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          },
          "primary": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          },
          "secondary": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          }
        },
        "text": {
          "inverse": {
            "$type": "color",
            "$value": "{color.base.neutrals.800}"
          },
          "muted": {
            "$type": "color",
            "$value": "{color.base.neutrals.400}"
          },
          "primary": {
            "$type": "color",
            "$value": "{color.base.neutrals.50}"
          },
          "secondary": {
            "$type": "color",
            "$value": "{color.base.neutrals.200}"
          }
        }
      },
      "focus": {
        "ring": {
          "$type": "color",
          "$value": "{color.base.primary.400}"
        }
      },
      "input": {
        "border": {
          "default": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "disabled": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "error": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "focus": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "hover": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          }
        },
        "icon": {
          "default": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "interactive": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          }
        },
        "surface": {
          "default": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "disabled": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "error": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "hover": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          }
        },
        "text": {
          "disabled": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "label": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "placeholder": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          },
          "value": {
            "$type": "color",
            "$value": "{color.base.primary.400}"
          }
        }
      }
    }
  },
  "radius": {
    "base": {
      "0": {
        "$type": "dimension",
        "$value": 0
      },
      "1": {
        "$type": "dimension",
        "$value": 4
      },
      "2": {
        "$type": "dimension",
        "$value": 8
      },
      "3": {
        "$type": "dimension",
        "$value": 12
      },
      "4": {
        "$type": "dimension",
        "$value": 16
      },
      "6": {
        "$type": "dimension",
        "$value": 24
      },
      "7": {
        "$type": "dimension",
        "$value": 32
      },
      "05": {
        "$type": "dimension",
        "$value": 2
      },
      "full": {
        "$type": "dimension",
        "$value": 9999
      }
    },
    "semantic": {
      "control": {
        "full": {
          "$type": "dimension",
          "$value": "{radius.base.full}"
        },
        "large": {
          "$type": "dimension",
          "$value": "{radius.base.3}"
        },
        "medium": {
          "$type": "dimension",
          "$value": "{radius.base.2}"
        },
        "sharp": {
          "$type": "dimension",
          "$value": "{radius.base.05}"
        },
        "small": {
          "$type": "dimension",
          "$value": "{radius.base.1}"
        }
      },
      "layer": {
        "2Xl": {
          "$type": "dimension",
          "$value": "{radius.base.7}"
        },
        "l": {
          "$type": "dimension",
          "$value": "{radius.base.4}"
        },
        "m": {
          "$type": "dimension",
          "$value": "{radius.base.3}"
        },
        "none": {
          "$type": "dimension",
          "$value": "{radius.base.1}"
        },
        "s": {
          "$type": "dimension",
          "$value": "{radius.base.2}"
        },
        "xl": {
          "$type": "dimension",
          "$value": "{radius.base.6}"
        }
      }
    }
  },
  "spacing": {
    "base": {
      "1": {
        "$type": "dimension",
        "$value": 8
      },
      "2": {
        "$type": "dimension",
        "$value": 16
      },
      "3": {
        "$type": "dimension",
        "$value": 24
      },
      "4": {
        "$type": "dimension",
        "$value": 32
      },
      "5": {
        "$type": "dimension",
        "$value": 40
      },
      "6": {
        "$type": "dimension",
        "$value": 48
      },
      "7": {
        "$type": "dimension",
        "$value": 56
      },
      "8": {
        "$type": "dimension",
        "$value": 64
      },
      "15": {
        "$type": "dimension",
        "$value": 12
      },
      "35": {
        "$type": "dimension",
        "$value": 28
      },
      "45": {
        "$type": "dimension",
        "$value": 36
      },
      "05": {
        "$type": "dimension",
        "$value": 4
      }
    },
    "semantic": {
      "control": {
        "height": {
          "large": {
            "$type": "dimension",
            "$value": "{spacing.base.5}"
          },
          "medium": {
            "$type": "dimension",
            "$value": "{spacing.base.45}"
          },
          "small": {
            "$type": "dimension",
            "$value": "{spacing.base.35}"
          }
        }
      },
      "gap": {
        "empty": {
          "$type": "dimension",
          "$value": "{spacing.base.8}"
        },
        "extraLarge": {
          "$type": "dimension",
          "$value": "{spacing.base.4}"
        },
        "icon": {
          "$type": "dimension",
          "$value": "{spacing.base.05}"
        },
        "large": {
          "$type": "dimension",
          "$value": "{spacing.base.3}"
        },
        "medium": {
          "$type": "dimension",
          "$value": "{spacing.base.2}"
        },
        "section": {
          "$type": "dimension",
          "$value": "{spacing.base.6}"
        },
        "small": {
          "$type": "dimension",
          "$value": "{spacing.base.1}"
        }
      },
      "inset": {
        "container": {
          "default": {
            "$type": "dimension",
            "$value": "{spacing.base.3}"
          },
          "extraTight": {
            "$type": "dimension",
            "$value": "{spacing.base.1}"
          },
          "loose": {
            "$type": "dimension",
            "$value": "{spacing.base.4}"
          },
          "tight": {
            "$type": "dimension",
            "$value": "{spacing.base.2}"
          }
        },
        "control": {
          "horizontal": {
            "default": {
              "$type": "dimension",
              "$value": "{spacing.base.2}"
            },
            "loose": {
              "$type": "dimension",
              "$value": "{spacing.base.3}"
            },
            "tight": {
              "$type": "dimension",
              "$value": "{spacing.base.1}"
            }
          },
          "vertical": {
            "default": {
              "$type": "dimension",
              "$value": "{spacing.base.1}"
            },
            "loose": {
              "$type": "dimension",
              "$value": "{spacing.base.15}"
            },
            "tight": {
              "$type": "dimension",
              "$value": "{spacing.base.05}"
            }
          }
        }
      },
      "screen": {
        "desktop": {
          "$type": "dimension",
          "$value": "{spacing.base.4}"
        },
        "mobile": {
          "$type": "dimension",
          "$value": "{spacing.base.2}"
        }
      }
    }
  },
  "typography": {
    "base": {
      "lineHeight": {
        "14": {
          "$type": "dimension",
          "$value": 14
        },
        "16": {
          "$type": "dimension",
          "$value": 16
        },
        "18": {
          "$type": "dimension",
          "$value": 18
        },
        "20": {
          "$type": "dimension",
          "$value": 20
        },
        "24": {
          "$type": "dimension",
          "$value": 24
        },
        "26": {
          "$type": "dimension",
          "$value": 26
        },
        "28": {
          "$type": "dimension",
          "$value": 28
        },
        "30": {
          "$type": "dimension",
          "$value": 30
        },
        "32": {
          "$type": "dimension",
          "$value": 32
        },
        "40": {
          "$type": "dimension",
          "$value": 40
        },
        "48": {
          "$type": "dimension",
          "$value": 48
        },
        "56": {
          "$type": "dimension",
          "$value": 56
        },
        "64": {
          "$type": "dimension",
          "$value": 64
        }
      },
      "size": {
        "12": {
          "$type": "dimension",
          "$value": 12
        },
        "14": {
          "$type": "dimension",
          "$value": 14
        },
        "16": {
          "$type": "dimension",
          "$value": 16
        },
        "18": {
          "$type": "dimension",
          "$value": 18
        },
        "20": {
          "$type": "dimension",
          "$value": 20
        },
        "24": {
          "$type": "dimension",
          "$value": 24
        },
        "32": {
          "$type": "dimension",
          "$value": 32
        },
        "40": {
          "$type": "dimension",
          "$value": 40
        },
        "48": {
          "$type": "dimension",
          "$value": 48
        },
        "56": {
          "$type": "dimension",
          "$value": 56
        },
        "64": {
          "$type": "dimension",
          "$value": 64
        }
      }
    },
    "semantic": {
      "lineHeight": {
        "2Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.28}"
        },
        "2Xs": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.14}"
        },
        "3Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.30}"
        },
        "4Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.32}"
        },
        "5Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.40}"
        },
        "6Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.48}"
        },
        "7Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.56}"
        },
        "8Xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.64}"
        },
        "l": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.24}"
        },
        "m": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.20}"
        },
        "s": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.18}"
        },
        "xl": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.26}"
        },
        "xs": {
          "$type": "dimension",
          "$value": "{typography.base.lineHeight.16}"
        }
      },
      "paragraphSpacing": {
        "2Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.2Xl}"
        },
        "2xS": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.2Xs}"
        },
        "3Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.3Xl}"
        },
        "4Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.4Xl}"
        },
        "5Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.5Xl}"
        },
        "6Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.6Xl}"
        },
        "7Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.7Xl}"
        },
        "8Xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.8Xl}"
        },
        "l": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.l}"
        },
        "m": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.m}"
        },
        "s": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.s}"
        },
        "xl": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.xl}"
        },
        "xs": {
          "$type": "dimension",
          "$value": "{typography.semantic.lineHeight.xs}"
        }
      },
      "size": {
        "2Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.20}"
        },
        "3Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.24}"
        },
        "4Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.32}"
        },
        "5Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.40}"
        },
        "6Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.48}"
        },
        "7Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.56}"
        },
        "8Xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.64}"
        },
        "l": {
          "$type": "dimension",
          "$value": "{typography.base.size.16}"
        },
        "m": {
          "$type": "dimension",
          "$value": "{typography.base.size.14}"
        },
        "s": {
          "$type": "dimension",
          "$value": "{typography.base.size.12}"
        },
        "xl": {
          "$type": "dimension",
          "$value": "{typography.base.size.18}"
        }
      }
    }
  }
} as const;
export type Tokens = typeof tokens;
export default tokens;
